apiVersion: v1
kind: Pod
metadata:
  name: private-image-test-1
  namespace: default
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  containers:
  - name: uses-private-image
    image: nginx:1.21.6
    imagePullPolicy: IfNotPresent
    command: ["echo", "SUCCESS"]
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi